### ISSUE TITLE
Dataset 404 Not Found

### ISSUE THREAD

**Issue by molsonc** [ghulten/MLLearning#1]
The dataset files are unavailable (404 Not Found)
http://parnec.nuaa.edu.cn/xtan/data/ClosedEyeDatabases.html
http://parnec.nuaa.edu.cn/xtan/data/datasets/dataset_B_Eye_Images.rar

**Comment by ghulten** [comment]
Thanks for the report! I've added a link to a mirror: https://intelligentsystem.io/learn/pytorch/data/blink.zip
